spring:
  application:
    name: rf-vehicle-ad-api
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/rf-vehicle-ad?createDatabaseIfNotExist=true&useSSL=false
    username: renanfretta
    password: Ren@nFretta1986
  jackson:
    time-zone: America/Sao_Paulo
    locale: pt_BR
